import { cx } from "class-variance-authority";
import { twMerge } from "tailwind-merge";

export const cn = (...inputs: Parameters<typeof cx>) => twMerge(cx(inputs));

// Export all components
export * from "./accordion";
export * from "./alert-dialog";
export * from "./avatar";
export * from "./badge";
export * from "./breadcrumb";
export * from "./button";
export * from "./calendar";
export * from "./card";
export * from "./chart";
export * from "./checkbox";
export * from "./collapsible";
export * from "./drawer";
export * from "./dropdown-menu";
export * from "./field";
export * from "./form";
export * from "./input";
export * from "./input-otp";
export * from "./password-input";
export * from "./label";
export * from "./popover";
export * from "./progress";
export * from "./radio-group";
export * from "./scroll-area";
export * from "./select";
export * from "./separator";
export * from "./sidebar";
export * from "./slider";
export * from "./switch";
export * from "./skeleton";
export * from "./table";
export * from "./tabs";
export * from "./textarea";
export * from "./theme";
export * from "./toast";
export * from "./toggle";
export * from "./toggle-group";
export * from "./tooltip";
